spring:
  flyway:
    enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/passbee?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: all4u_app
    password: Passbee!2025
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

# 외부 API (그대로 유지)
external:
  qnet:
    base-url: "http://openapi.q-net.or.kr/api/service/rest"
    service-key: "9tIoGU5QNqm7uVeqgQXftWdCxmc1iGAqn86rHbQh5BZmGUgdlpc8sq5SwgeQIwgPyM5Rn0o//C7pnYa0cE/ycA=="
    endpoints:
      total-exam: "InquiryStatSVC/getTotExamList"
      grad-pi-exam: "InquiryStatSVC/getGradPiExamList"
      grad-pi-pass: "InquiryStatSVC/getGradPiPassList"
      grad-si-exam: "InquiryStatSVC/getGradSiExamList"
      grad-si-pass: "InquiryStatSVC/getGradSiPassList"
      event-year-pi: "InquiryStatSVC/getEventYearPiList"
      event-year-si: "InquiryStatSVC/getEventYearSiList"
      event-cert-year: "InquiryStatSVC/getEventCertYearList"
      cert-year-grade: "InquiryStatSVC/getCertYearGradeList"
      cert-year-age: "InquiryStatSVC/getCertYearAgeList"
      qualifications: "InquiryListNationalQualifcationSVC/getList"
      qualitative-info: "InquiryQualInfo/getList"
      exam-subjects: "InquiryExamKmInfo/getList"
      practical-items: "InquiryPractExamCarrySVC/getList"
      agencies: "InquiryRcogInstiSVC/getList"
      regional-reception: "InquiryExameeAbdSVC/getList"
      score-distribution: "InquiryRecptScoreDistSVC/getList"


# JWT (dev에도 동일 값으로 명시: 프로필 우선순위상 이 값이 최종 적용됨)
jwt:
  secret: "6uhYWG9E97SkYIjATdnemWqSacbJM9CBL0e00PbvABkRqvWu4+nRE7w4dXOn1NLe
JE8FSCAPpVVJAKmi/fOvyg=="
  expiration-ms: 3600000