spring:
  profiles:
    active: dev        # 기본 프로필을 dev로
  flyway:
    enabled: true
    locations: classpath:db/migration   # 스크린샷 경로와 동일
  jpa:
    hibernate:
      ddl-auto: none   # 스키마는 Flyway가 관리
    open-in-view: false

server:
  port: 8080