spring:
  datasource:
    url: jdbc:mysql://localhost:3307/passbee?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: passbee
    password: passbee
  jpa:
    hibernate.ddl-auto: update   # 개발 중 자동 생성
    open-in-view: false
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

logging.level.org.hibernate.SQL: warn