spring:
  datasource:
    url: jdbc:mysql://localhost:3307/passbee?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root1234!!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # 애플리케이션을 실행할 때마다 DB 새로 생성. 실제 운영 서버에서는 update로 수정
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  jackson:
    deserialization:
      fail-on-unknown-properties: false

external:
  qnet:
    base-url: "http://openapi.q-net.or.kr/api/service/rest"
    service-key: "9tIoGU5QNqm7uVeqgQXftWdCxmc1iGAqn86rHbQh5BZmGUgdlpc8sq5SwgeQIwgPyM5Rn0o//C7pnYa0cE/ycA==" # 공공데이터포털의 본인 디코딩 키

    endpoints:
      ##### 국가기술자격 통계 정보 (InquiryStatSVC) #####
      # 연도별 응시자/합격자 수
      total-exam: "InquiryStatSVC/getTotExamList"
      # 연도별 등급별 필기 응시자 수
      grad-pi-exam: "InquiryStatSVC/getGradPiExamList"
      # 연도별 등급별 필기 합격률
      grad-pi-pass: "InquiryStatSVC/getGradPiPassList"
      # 연도별 등급별 실기 응시자 수
      grad-si-exam: "InquiryStatSVC/getGradSiExamList"
      # 연도별 등급별 실기 합격률
      grad-si-pass: "InquiryStatSVC/getGradSiPassList"
      # 종목별 연도별 필기 현황
      event-year-pi: "InquiryStatSVC/getEventYearPiList"
      # 종목별 연도별 실기 현황
      event-year-si: "InquiryStatSVC/getEventYearSiList"
      # 종목별 자격취득자 연도별 성별 현황
      event-cert-year: "InquiryStatSVC/getEventCertYearList"
      # 자격취득자 연도별 등급별 수
      cert-year-grade: "InquiryStatSVC/getCertYearGradeList"
      # 자격취득자 연도별 연령별 수
      cert-year-age: "InquiryStatSVC/getCertYearAgeList"

      ##### 개별 API #####
      # 1. 국가 자격 종목 목록 정보
      qualifications: "InquiryListNationalQualifcationSVC/getList"
      # 2. 국가기술자격 종목 상세 정보
      qualitative-info: "InquiryQualInfo/getList"
      # 3. 국가자격 시험교시 과목 정보
      exam-subjects: "InquiryExamKmInfo/getList"
      # 4. 실기시험 지참물 정보
      practical-items: "InquiryPractExamCarrySVC/getList"
      # 5. 자격정보 인정 기관 정보
      agencies: "InquiryRcogInstiSVC/getList"
      # 6. 거주지별 기술자격 시험접수 현황
      regional-reception: "InquiryExameeAbdSVC/getList"
      # 7. 연도별 회별 국가기술자격시험 원서 점수 분포
      score-distribution: "InquiryRecptScoreDistSVC/getList"