spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/passbee?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: passbee
    password: Passbee!2025
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    repair-on-migrate: true
    encoding: UTF-8
    table: flyway_schema_history

  jpa:
    hibernate:
      ddl-auto: update
      # MySQLDialect는 자동 선택되니 아래 줄은 아예 지워도 됩니다.
      # naming.physical-strategy 는 여기가 아니라 바로 아래처럼 지정해야 해요.
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # 경고 없애려면 다음 줄 삭제하거나 org.hibernate.dialect.MySQLDialect 로 변경
        # dialect: org.hibernate.dialect.MySQLDialect
    # ✅ 네이밍 전략은 여기!
    #   org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    #   => userName -> user_name
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  jackson:
    deserialization:
      fail-on-unknown-properties: false

  # ✅ 중첩 제거 (mail.mail ❌)
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.hibernate.SQL: warn

# ✅ management 는 최상위 레벨로
management:
  endpoints:
    web:
      exposure:
        include: health,mappings
  endpoint:
    health:
      show-details: always

jwt:
  access-secret: 95d978e35ebdb5351a0a9da337ffb62100e469473cedd7be6648063c1eda3115
  access-ttl-ms: 3600000

external:
  qnet:
    base-url: "http://openapi.q-net.or.kr/api/service/rest"
    service-key: ${QNET_SERVICE_KEY}
    endpoints:
      total-exam: "InquiryStatSVC/getTotExamList"
      grad-pi-exam: "InquiryStatSVC/getGradPiExamList"
      grad-pi-pass: "InquiryStatSVC/getGradPiPassList"
      grad-si-exam: "InquiryStatSVC/getGradSiExamList"
      grad-si-pass: "InquiryStatSVC/getGradSiPassList"
      event-year-pi: "InquiryStatSVC/getEventYearPiList"
      event-year-si: "InquiryStatSVC/getEventYearSiList"
      event-cert-year: "InquiryStatSVC/getEventCertYearList"
      cert-year-grade: "InquiryStatSVC/getCertYearGradeList"
      cert-year-age: "InquiryStatSVC/getCertYearAgeList"
      qualifications: "InquiryListNationalQualifcationSVC/getList"
      qualitative-info: "InquiryQualInfo/getList"
      exam-subjects: "InquiryExamKmInfo/getList"
      practical-items: "InquiryPractExamCarrySVC/getList"
      agencies: "InquiryRcogInstiSVC/getList"
      regional-reception: "InquiryExameeAbdSVC/getList"
      score-distribution: "InquiryRecptScoreDistSVC/getList"

app:
  mail:
    from: PassBee <no-reply@passbee.local>
    base-url: http://localhost:8080